import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

import "../src/styles/globals.css";
import { ReactNode } from "react";
import Navbar from "@/src/components/Navbar/Navbar";
import Provider from '@/src/components/Provider/Provider';
interface IProps {
  children: ReactNode;
}
export const metadata = {
  title: 'desi buck',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#efeeee]`}>
        <Provider>
          <Navbar/>
          {children}
        </Provider>
      </body>yan
    </html>
  );
}
